# Generated by Django 4.0.1 on 2022-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='dat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
