# Generated by Django 4.0.1 on 2022-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(),
        ),
    ]
