# Generated by Django 4.0.1 on 2022-01-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0002_alter_employees_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
