# Generated by Django 4.0.1 on 2022-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0003_delete_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('paidamount', models.FloatField()),
                ('paidmonth', models.CharField(max_length=100)),
            ],
        ),
    ]
