# Generated by Django 4.0.1 on 2022-01-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0003_rename_employees_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
    ]
