# Generated by Django 4.0.1 on 2022-01-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='def', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
