# Generated by Django 4.0.1 on 2022-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0005_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
