# Generated by Django 4.0.1 on 2022-01-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0006_alter_employee_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lname',
            new_name='lastname',
        ),
    ]
