# Generated by Django 4.0.1 on 2022-01-16 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hrms', '0007_rename_fname_employee_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pday', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
